### ISSUE TITLE
Could not find the module in the React Client Manifest

### ISSUE THREAD

**Issue by pnodet** [moshest/next-client-cookies#10]
Hi!

I'm running into the following error, any lead on how this may be solved?

Error: Could not find the module "/node_modules/.pnpm/next-client-cookies@1.1.0_next@14.0.3_react@18.2.0/node_modules/next-client-cookies/dist/provider.mjs#SecureCookiesProvider" in the React Client Manifest. This is probably a bug in the React Server Components bundler.

**Comment by moshest** [comment]
What's your current setup? Did you try delete `node_modules` and reinstall?

I have other Next.js projects that are working so I guess it's something in PNPM caching?

**Comment by moshest** [comment]
Closing as idle
