### ISSUE TITLE
Error `cookies() expects to have requestAsyncStorage, none available` using `useCookies`

### ISSUE THREAD

**Issue by pzxmsry** [moshest/next-client-cookies#11]
Whenever I wrap my application in `CookiesProvider` imported from "next-client-cookies/server", I receive this error.
I was not calling `useCookies` or `cookies` anywhere, so, what might be the problem?

**Comment by moshest** [comment]
You should place the `CookiesProvider` within the root `layout.tsx` file. This file must be a server component.

Also, what's your Next.js version?

**Comment by pzxmsry** [comment]
My Next.js version is 14.0.2, and you were right, when I placed it in a separate providers server component, everything worked. Thank you!
