### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by hdwv** [moshest/next-client-cookies#12]
NextJS 14.0.4

<img width="802" alt="Screenshot 2023-12-11 at 3 20 13 p m" src="https://github.com/moshest/next-client-cookies/assets/149725529/16fbc049-0e2c-4ac1-a4ed-31d930d6167e">

**Comment by moshest** [comment]
Can't reproduce, [our demo](https://github.com/moshest/next-client-cookies/tree/main/demo) works well.
