### ISSUE TITLE
Document that CookieProvider bails out the route segment from static generation

### ISSUE THREAD

**Issue by mordechaim** [moshest/next-client-cookies#16]
I noticed while building my application that the entire app now opted out of static generation. 
After debugging the problem I concluded the cause to be wrapping the root layout with `<CookieProvider>`.

In my case, I only needed client cookies on a single page, so wrapping the root was an overkill. 

I think it would be beneficial to document this.

**Comment by moshest** [comment]
Added: https://github.com/moshest/next-client-cookies/commit/de68ab7dd29b7f3b5c89158176963e729a8f9837
