### ISSUE TITLE
'CookiesProvider' cannot be used as a JSX component. Next 15

### ISSUE THREAD

**Issue by Fouadktb** [moshest/next-client-cookies#24]
as the Title implies, getting type error, 

`'CookiesProvider' cannot be used as a JSX component.
  Its type '({ children, }: { children: ReactNode; }) => Promise<ReactElement<any, string | JSXElementConstructor<any>>>' is not a valid JSX element type.`

**Comment by moshest** [comment]
Please check the demo folder, it seems that you created a client component on layout instead of a server component.
