### ISSUE TITLE
Error "missing required error components, refreshing..."

### ISSUE THREAD

**Issue by IonelLupu** [moshest/next-client-cookies#3]
I am on NextJS 13.4.19. I get this error when I do everything from the Readme. The app doesn't do anything:
![image](https://github.com/moshest/next-client-cookies/assets/4083652/b0544d8d-986b-442a-b333-aada4d9b3826)
![image](https://github.com/moshest/next-client-cookies/assets/4083652/1e4a07f4-a7e1-45e2-84a4-2c979ce53864)

**Comment by moshest** [comment]
Hi @IonelLupu ,

Thank you for reporting. This library working with many other projects and applications and I think there is something on your setup that causing this issue.

I've added a demo project here so you can see an example of a working setup: https://github.com/moshest/next-client-cookies/tree/main/demo

If you still having an issue, please create a reproduction project and send here a link. I'm closing this issue until more details provided.

**Comment by IonelLupu** [comment]
@moshest  not sure what happened, but now it works. I installed different versions of nextjs. Not sure which one was the issue. All good. thx
